{{/*
Copyright 2019 HAProxy Technologies LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.defaultBackend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ template "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  {{- if not .Values.defaultBackend.autoscaling.enabled }}
  replicas: {{ .Values.defaultBackend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.defaultBackend.podLabels }}
{{ toYaml .Values.defaultBackend.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.defaultBackend.podAnnotations }}
      annotations:
{{ toYaml .Values.defaultBackend.podAnnotations | indent 8 }}
      {{- end }}
    spec:
{{- with .Values.defaultBackend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- if .Values.defaultBackend.imageCredentials.registry }}
      imagePullSecrets:
      - name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
{{- else if .Values.defaultBackend.existingImagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.defaultBackend.existingImagePullSecret }}
{{- end }}
{{- if .Values.controller.priorityClassName }}
      priorityClassName: {{ .Values.controller.priorityClassName }}
{{- end }}
      containers:
        - name: {{ template "kubernetes-ingress.name" . }}-{{ .Values.defaultBackend.name }}
          image: "{{ .Values.defaultBackend.image.repository }}:{{ .Values.defaultBackend.image.tag }}"
          imagePullPolicy: {{ .Values.defaultBackend.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.defaultBackend.image.runAsUser }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            {{- if .Values.defaultBackend.enableRuntimeDefaultSeccompProfile }}
            seccompProfile:
              type: RuntimeDefault
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.defaultBackend.containerPort }}
              protocol: TCP
          {{- if .Values.defaultBackend.extraEnvs }}
          env:
            {{- toYaml .Values.defaultBackend.extraEnvs | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.defaultBackend.resources | nindent 12 }}
      {{- with .Values.defaultBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.defaultBackend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "kubernetes-ingress.defaultBackend.serviceAccountName" . }}
      terminationGracePeriodSeconds: 60
    {{- with .Values.defaultBackend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
